package capstone;

/**
 * Represents a category in the restaurant menu. Each
 * category has a unique ID, a heading, and a description.
 * 
 * @author angel
 */
public class Category {
	private int cateId;  // Unique ID for the category
	private String heading;  // Name of the category
	private String description;  // Description of the category

	/**
	 * Constructor to create a Category with a specified ID.
	 * 
	 * @param category_id               the ID of the category
	 * @param heading                   the name of the category
	 * @param description               the description of the category
	 * @throws IllegalArgumentException if the heading or description is null or empty
	 */
	public Category(int category_id, String heading, String description) {
		if (heading == null || heading.trim().isEmpty()) {
			throw new IllegalArgumentException("Category name cannot be null or empty.");
		}
		if (description == null || description.trim().isEmpty()) {
			throw new IllegalArgumentException("Category description cannot be null or empty.");
		}
		this.cateId = category_id;
		this.heading = heading;
		this.description = description;
	}

	/**
	 * Constructor to create a Category without specifying
	 * an ID. The ID will be auto-generated by the database.
	 * 
	 * @param heading                   the name of the category
	 * @param description               the description of the category
	 * @throws IllegalArgumentException if the heading or description is null or empty
	 */
	public Category(String heading, String description) {
		if (heading == null || heading.trim().isEmpty()) {
			throw new IllegalArgumentException("Category name cannot be null or empty.");
		}
		if (description == null || description.trim().isEmpty()) {
			throw new IllegalArgumentException("Category description cannot be null or empty.");
		}
		this.heading = heading;
		this.description = description;
	}

	/**
	 * Gets the ID of the category.
	 * 
	 * @return the ID of the category
	 */
	public int getId() {
		return cateId;
	}

	/**
	 * Gets the heading of the category.
	 * 
	 * @return the name of the category
	 */
	public String getName() {
		return heading;
	}

	/**
	 * Sets the heading of the category.
	 * 
	 * @param heading                   the new name of the category
	 * @throws IllegalArgumentException if the heading is null or empty
	 */
	public void setName(String heading) {
		if (heading == null || heading.trim().isEmpty()) {
			throw new IllegalArgumentException("Category name cannot be null or empty.");
		}
		this.heading = heading;
	}

	/**
	 * Gets the description of the category.
	 * 
	 * @return the description of the category
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description of the category.
	 * 
	 * @param description               the new description of the category
	 * @throws IllegalArgumentException if the description is null or empty
	 */
	public void setDescription(String description) {
		if (description == null || description.trim().isEmpty()) {
			throw new IllegalArgumentException("Category description cannot be null or empty.");
		}
		this.description = description;
	}

	/**
	 * Provides a string representation of the category, including its ID, name, and description.
	 * 
	 * @return a string representation of the category
	 */
	@Override
	public String toString() {
		return "Category{id=" + cateId + ", name='" + heading + "', description='" + description + "'}";
	}

	/**
	 * Checks if this category is equal to another object. Two categories
	 * are considered equal if they have the same ID, name, and description.
	 * 
	 * @param obj   the object to compare
	 * @return true if the categories are equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null || getClass() != obj.getClass()) return false;
		Category categories = (Category) obj;
		return cateId == categories.cateId && heading.equals(categories.heading) && description.equals(categories.description);
	}

	/**
	 * Computes the hash code of the category based on its ID, name, and description.
	 * 
	 * @return the hash code of the category
	 */
	@Override
	public int hashCode() {
		int result = Integer.hashCode(cateId);
		result = 31 * result + heading.hashCode();
		result = 31 * result + description.hashCode();
		return result;
	}
}
