package capstone;

/**
 * Represents an item in the restaurant menu. The Item class stores details
 * about a menu item, including its name, description, price, and category.
 * 
 * @author angel
 */
public class Item {
    private int id;
    private String name;
    private String description;
    private float price;
    private int categoryId;

    /**
     * Constructs an Item object with an id, name, description, price, and category ID.
     * 
     * @param item_id     The unique identifier of the item.
     * @param name        The name of the item.
     * @param description A description of the item.
     * @param price       The price of the item.
     * @param category_id The category ID of the item.
     */
    public Item(int item_id, String name, String description, float price, int category_id) {
        this.id = item_id;
        setName(name);
        setDescription(description);
        setPrice(price);
        setCategoryId(category_id);
    }

    /**
     * Constructs an Item object with name, description, price, and category ID.
     * The id will be generated by the database or model when the item is persisted.
     * 
     * @param name        The name of the item.
     * @param description A description of the item.
     * @param price       The price of the item.
     * @param category_id The category ID of the item.
     */
    public Item(String name, String description, float price, int category_id) {
        setName(name);
        setDescription(description);
        setPrice(price);
        setCategoryId(category_id);
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    /**
     * Sets the name of the item.
     * 
     * @param name                      The name of the item.
     * @throws IllegalArgumentException if the name is null or empty.
     */
    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Name cannot be null or empty.");
        }
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the item.
     * 
     * @param description               The description of the item.
     * @throws IllegalArgumentException if the description is null or empty.
     */
    public void setDescription(String description) {
        if (description == null || description.trim().isEmpty()) {
            throw new IllegalArgumentException("Description cannot be null or empty.");
        }
        this.description = description;
    }

    public float getPrice() {
        return price;
    }

    /**
     * Sets the price of the item.
     * 
     * @param price                     The price of the item.
     * @throws IllegalArgumentException if the price is negative.
     */
    public void setPrice(float price) {
        if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative.");
        }
        this.price = price;
    }

    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the category ID of the item.
     * 
     * @param category_id               The category ID of the item.
     * @throws IllegalArgumentException if the category ID is less than or equal to 0
     */
    public void setCategoryId(int category_id) {
        if (category_id <= 0) {
            throw new IllegalArgumentException("Category ID must be positive.");
        }
        this.categoryId = category_id;
    }

    /**
     * Returns a string representation of the item.
     * 
     * @return A string representation of the item
     */
    @Override
    public String toString() {
        return "Item{id=" + id + ", name='" + name + "', description='" + description +
               "', price=" + price + ", category_id=" + categoryId + "}"; 
    }

    /**
     * Compares this item to another object for equality.
     * 
     * @param obj   The object to compare this item with
     * @return true if the items are equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Item items = (Item) obj;
        return id == items.id && Float.compare(items.price, price) == 0 &&
               categoryId == items.categoryId && name.equals(items.name) &&
               description.equals(items.description);
    }

    /**
     * Returns a hash code value for this item.
     * 
     * @return A hash code value for this item
     */
    @Override
    public int hashCode() {
        return Integer.hashCode(id);
    }
}
